let kullaniciAdi = prompt("Adınız nedir ?");

let evetHayir = prompt(`Merhaba ${kullaniciAdi} Hikaye oyununa başlamaya hazır mısın ? (evet ya da hayır diyerek cevap vermelisin)`);

if (evetHayir.toLowerCase() === "evet") {
    alert("O zaman hikayeye başlıyoruz ");
} else {
    alert("O zaman hazırlan ve 'evet' de");
    throw new Error //devam etmesini istemediğim için araştırarak buldum hocam :)
}

alert("Meslekleri dedektiflik olan 2 arkadaş Nihat ve Koray, yine büronun yanındaki kafeden kahvelerini alıp sıradaki davayı çözmeye gittiler, olayın olduğu yere yaklaştıkça insan konuşmaları, korku içinde düşünen insanlar ve oraya buraya koşup 'GERÇEK DEĞİL Dİ Mİ?' diye soran insanların sayısı artıyordu, Nihat 'Sanırım çok büyük bir cinayet, insanlar çok gerilmiş, olanları görmek bizi de ürkütür mü dersin?' dedi ve gülerek elini Koray’ın omzuna attı, 'Ne davalar çözdük seninle, peşimizde seri katiller dolandı, hatırlamıyor musun alnımdaki silahı ve senin tedirgin bakışını?' dedi ve o da güldü, olay yerine daha hızlı varmaya karar verdiler ve olay yerinin olduğu lunaparka geldiler, herhangi bir vahşet, herhangi bir kan donduran olay yoktu; sadece ölen bir insan vardı, cesede doğru yürüdüler, ekipler onları bantın arkasına aldı ve cesetten önce acil bir şekilde görgü tanığına yönlendirdiler, Koray ve Nihat’ın dikkatini çeken şey, ortada büyük bir cinayet olmamasına rağmen görgü tanığının sürekli etrafa bakıp delirmiş bir şekilde gözlerini hareket ettirmesiydi, Nihat sorusunu sormak için yaklaştı: 'Merhaba hanımefendi, sizi bu kadar ko—' sözünü kesen kadın telaşla, 'O kafasında garip şekil barındıran bir varlıktı, yeşil renkli bir canavar gibiydi, onu saniyeler içinde 15-16 defa bıçakladı ve sonra koşarak yok oldu' dedi, 'Öncelikle sakin olun lütfen, garip bir canavarın bu çocuğu 15-16 defa bıçakladığını söylüyorsunuz ve saniyeler içerisinde bunu net gördüğünüze emin misiniz?' dedi Nihat, 'EVET, EMİNİM! LÜTFEN YARDIM EDİN, O HER YERDE OLABİLİR, LÜTFEN, YALVARIRIM!' diye bağırdı kadın, Nihat onun çok büyük bir şok içinde olduğunu düşünüyordu, belki de maskeli yeşil giyen bir adamdan bahsediyordu ve bu telaşı yüzünden ona saniyelerin bu kadar kısa geldiğini düşündü, Koray’ı köşeye çekti ve aralarında bu konuyu tartıştılar")

let firstChoise = prompt("Sizce onlar lunaparkta katili aramaya mı çalışmalı yoksa bu olayla bağlantılı olduğu düşünülen farklı bir olay yerine mi gitmeliler? (seçimini yap '1' mi '2' mi ?)")

if ( firstChoise === "1") {
    alert("Lunaparkta kalmaya devam ettiler; olay yeri sakinleştiğinde daha dikkatli bir araştırma yaptılar Nihat çalan telefonlarını kapatıp bu olaya fokuslanmıştı ve çocuğun sürünerek biraz yol katettiğini fark ettiler; damlayan kan izlerini takip ettiklerinde yolun dönme dolaba ulaştığını gördüler fakat dönme dolap hâlâ hareket ediyordu ve içinde parlayan yeşil bir ışık vardı; bir anda çığlık sesleri yükseldi, hemen oraya koştular ve yalnızca tek bir ceset değil, orada bulunan herkesin kanlar içinde yattığını gördüler; arkalarından yeşil bir ışık hızla yaklaşıyordu ve o anda mor renkli bir canavar Koray’ın önünde belirdi; Koray silahına davranıp elindeki bıçağa bir el ateş etti, Nihat’ın önündeki ışık yaklaştıkça görgü tanığının tarif ettiği canavar olduğu anlaşıldı; ‘Yok artık... bu Dipsy!’ dedi Nihat; Dipsy, bir çocuk programı olan Teletabiler’in yeşil renkli üyesiydi; Nihat bunu fark etmişti fakat Dipsy çok hızlıydı, yanından geçerken omzuna bir bıçak darbesi bıraktı; Koray mor renkli canavara bir el daha ateş edip onu yere yığdı; Nihat hızla arkasını dönüp bir kez daha şaşırdı ve 'Ne?! Bu Tinky Winky!' dedi; Tinky Winky, Teletabiler’in en büyüğü ve mor renkli olanıydı; bedeni sürekli kaybolup yeniden beliriyordu.");
} else {
    alert("Nihat'a bir telefon gelir: 'Nihat, Koray'ı da al ve çabuk buraya gelin, burada inanılmaz şeyler yaşanıyor, biri bizi izliyor Nihat, insanlar birbirini öldürüyor, ortalık kan gölüne döndü, yetişin.' Nihat telaşla Koray'a bakarak 'Tamam, sakin olun, hemen yola çıkıyoruz.' der ve hemen bir ekip otosuna atlayıp oradaki olay yerine giderler. Olay yeri bir kreş olmasına rağmen, içeriden gelen güzel yemek ya da kurşun boyama kalemi kokuları yerine etrafı kan kokusu sarmıştır. İkisi de silahlarını ellerine alıp kapıdan içeri girerler. Kreşteki cesetler, lunaparktaki gibi birçok kez bıçaklanmıştır. Üst kata çıktıklarında, Nihat konuştuğu ekip arkadaşının da cesedini görünce aşırı sinirlenir. Koray onu geri çeker: 'Bu kadar sinirlenirsen bu işi elimize yüzümüze bulaştıracağız, yapma.' der. Nihat ise 'Umrumda değil, o benim arkadaşım, bunu normal karşılamamı mı bekliyorsun? Bunca ceset beni aşırı sinirlendirdi, sinirlenmeyerek saçmalığa imza atan sensin.' diyerek çıkışır. Bu tartışma ikisini farklı yollara iter. Koray, solundaki odaya girip fazla yara almamış bir bedeni inceler, hâlâ yaşıyor olabileceğini düşünürken bir anda sırtına bir bıçak saplanır. Acı içinde silahını düşürür, arkasına baktığında ise daha büyük bir acı yaşar: onu bıçaklayan kişi Nihat'tır. Koray acı içindeyken bir de bu ihanetin acısı eklenmiştir. O sırada bir silah sesi duyulur ve Nihat'ın kafasını delip geçen bir mermi tavana sekip Koray'ın önüne düşer. Nihat Koray'ın üstüne yığılır. Koray, silahı ateşleyen kişiye baktığında, onun da Nihat olduğunu görür. Gerçek Nihat hızla yanına gelirken, onu bıçaklayan sahte Nihat kırmızı renkli bir canavara dönüşür. Nihat onu tanır: bu, Teletabiler'in kırmızı ve en küçük üyesi Po'dur. Nihat, Koray'ın yarasına bakar. Koray ise zorlukla konuşur: 'Hiç umutlanma,")
    alert("bıçak kalbime saplandı, burada can vereceğim.' Nihat gözyaşlarını tutamaz. 'Görgü tanığıda yeşil canavardan bahsetmişti onlardan 2 tane daha var kalk' desede Koray son nefesini vermiştir . Nihat, alnından süzülen ter ve gözyaşlarıyla kamera odasına koşar ve son Teletabi olan Laa-Laa'yı görür. Ancak Laa-Laa kameraya gözlerini diktiği anda, tüm kameralar çalışmayı durdurur çünkü sigortaları kapatmıştır. Nihat, ekip arkadaşının sözlerini hatırlar: Laa-Laa onu izliyordu. Eline silahı alır ve onu aramaya başlar, ama onu gören birini nasıl alt edecekti ki? Bunları düşünürken, Koray'ın silahını eline geçiren Laa-Laa, Nihat'ı pencerenin camından vurur. Nihat orada can verir")
    alert("Malesef hikayedeki baş roller bu seçiminle ecellerine doğru yürüdüler ve hikayemiz bitti oynadığın için teşekkür ederim")
    throw new Error
}

let secondChoise = prompt("Koray, Nihat'ın anlattıklarına anlam veremezken kolundan akan kanları gördü: 'Şuraya otur, o yarayı sarayım.' dedi. Fakat Nihat, 'Onların iki üyesi daha var, onlar nerede? Onları aramalıyız, yarayı boşver.' diyerek yarasını önemsemek istemedi. Sizce 1) Koray'ın yarasını sarmasına izin mi vermeli, 2) İzin vermeyip onları aramaya devam mı etmeli? (Seçimini yap '1' mi '2' mi?)")

if (secondChoise === "2") {
    alert("Nihat yarasına aldırış etmez, Koray da onu bu konuda zorlamaz; sürekli Nihat'ın telefonunu çaldıran ekip arkadaşı yanlarına yaklaşır: 'Elli kere çaldırdım o telefonu, neden açmıyorsun?' der. Nihat da sinirlenerek, 'Sen burada bizim ne ile uğraştığımızı zannediyorsun? Garip garip varlıklarla karşı karşıya kaldık, birçok insan öldü, şunlara bak, Teletabi denilen canavarlar... Ölüler orada, git de gör.' Ekip arkadaşları cesetleri inceler, yüzünü garip bir ifade bürümüştür. Koray o sırada adamın kemerindeki bıçağı fark eder; ekip içinde asla bıçak kullanılmaz. Koray bunu gözleriyle Nihat'a gösterir.")
} else {
    alert("Nihat, sonradan Koray'ın sözlerinin mantıklı olduğunu düşünüp yarasını sarmasına izin verir ve onlar otururken, sürekli onun telefonunu çaldıran ekip arkadaşı yanlarına gelir: 'Nihat, neredeydiniz? Elli kere aradım, açmadın.' der. Nihat, 'Burada neler oldu biliyor musun? Katil Teletabiler bir çocuğu öldürüyor, bize saldırıyorlar, saçma sapan işler... Ne olduğu hakkında en ufak fikrimiz yok, baksana şu yatanlara.' diyerek ne durumda olduklarını az da olsa açıklar. Ekip arkadaşı yanlarına oturur, Nihat'ın silahına bakarak onu yanındaki yerden alır: 'Nihat, bu silah ekibe yeni mi dağıtıldı? Kabzası baya güzelmiş.' diyerek Koray'ın kafasına bir el ateş eder ve Nihat'ı iterek yere yığar; namluyu kafasına dayadıktan sonra şu sözleri söyler: 'Arkadaşlarımı öldürmeyecektin.' Bedeni bir anda değişerek Teletabiler'in kırmızı üyesi olan 'Po'ya dönüşür, Nihat'a konuşma hakkı vermeden orada işini bitirir ve arkasını dönmeden yoluna devam eder.")
    alert("Malesef hikayedeki baş roller bu seçiminle ecellerine doğru yürüdüler ve hikayemiz bitti oynadığın için teşekkür ederim")
    throw new Error
}

let thirdChoise = prompt("Sizce o hain mi (evet ise 1, hayır ise 2 yazın).")

if (thirdChoise === "2") {
    alert("Nihat bu durumun onun hain olduğunu kanıtlamayacağını düşünür, sonuçta katiller Teletabi denilen varlıklar, o ise bir insandır; Koray'a bunu sessizce fısıldar ve bu durum Koray'ın aklını karıştırsa da bu düşünceyi arka plana atar. Koray, 'Ben şu dönme dolabın hâlâ neden çalıştığına bakacağım, kendine göz kulak ol,' der Nihat'a. Nihat kafasıyla onaylar ve ekip arkadaşının yanına yürür. Koray dönme dolabı incelerken camından, duvarın arkasında yansıyan sarı büyük bir şey görür; bu sarı şey duvardan onu izliyor gibi gözükür. Eliyle silahını tutar ve uzaktan Nihatlara doğru bakar; duvarın arkasına ateş etmek ya da bunu onlara söylemek arasında karar vermesi gerekiyordur.")
} else {
    alert("Nihat eline silahını alır ve hemen ona doğrultur: 'Ellerini kaldır!' diye bağırır; ekip arkadaşı buna anlam veremez ve 'Nihat, ne yapıyorsun? Neden o silahı bana doğrulttun?' der. Nihat, 'O cebindeki bıçağın sende ne işi var? Bizim ekibimizde bıçak taşınmaz, hem o bıçak bu Teletabilerin elindekiyle aynı,' der. Bu sohbetler dönerken bu kadar zamandır dönen dönme dolap durur, ışıklar kapanır. Nihat ekip arkadaşına doğru üç el ateş eder, Koray cebinden feneri çıkartır, etrafa tutmaya başlar; sarı renkli bir şey görür. Bu, Teletabilerin sarı renkli olan ekip üyelerinden 'Laa-Laa'dır. Koray onun hızlı olmadığını fark edip ona doğru nişan almaya başlar ama o her şeyi görüyor gibi ağaçların arkasına saklanır. Yerde yatan adam kırmızı renkli bir canavara dönüşür; bu, Teletabilerin bir diğer ve sonuncu üyesi 'Po'dur. Neyse ki mermilerden biri kalbine isabet etmiştir. Nihat silahını Laa-Laa'ya doğru tutarak bir el ateş eder ve ayağından vurur. Koray, yavaşlayan Laa-Laa'ya bir el daha ateş ederek onu yere yığar ve Laa-Laa da orada can verir. Nihat derin bir nefes alarak, 'Dostum, onların üyeleri bu kadar, başka bir katil olamaz,' der. Koray da, 'Umarım yoktur,' cevabını verir ve iki usta dedektif olarak birbirlerine bakıp ağlamakla gülmek arası kahkahalar atarlar.")
    alert("Hikayemiz burada bitmedi Yeşil olan teletabi hala ortalıkta yok arkadaşlarının intikamını alıcak mı yoksa kendi hayatına mı bakıcak her şey bölüm 2 de ...")
    throw new Error
}

let fourthChoise = prompt("Sizce duvarın arkasına ateş mi etmeli yoksa bunu hızlıca onlara söylemeli mi (söylesin diyorsanız 1, söylemesin diyorsanız 2 yazın")

if (fourthChoise === "1") {
    alert("Koray sakin adımlarla Nihatlara doğru yaklaşmaya başlar, Nihat cesetleri incelerken ekip arkadaşının arkasında durduğunu görür fakat bir de görür ki bıçağı eline almış; Nihat'a seslenir: 'Nihat dikkat et, elinde bıçak var!' Nihat hızla kalkarken gözlerinin önünden bir bıçak savrulur, Nihat cebindeki silaha davranarak ekip arkadaşını karnından vurur, ardından bir tekme ile yere savurur; ekip arkadaşının bedeni kırmızılaşıp bozulmaya başlar, bu şey ekip arkadaşı değil, Teletabilerin kırmızı üyesi olan 'Po'dur. Nihat bir el daha ateş edip Koray'a bakar; Koray, duvarın arkasında sarı bir canavar daha olduğunu söylemeye yeltenirken kafasına bir bıçak saplanır, Nihat Koray yere düşerken arkasından bıçağı saplayan sarı canavara bir el ateş eder, kafasından vurur ve onu öldürür. Hızla koşarak Koray'ı kontrol eder ama Koray çoktan kafasındaki bıçak ile ölmüştür; sarı canavara da baktığında tahmin ettiği gibi Teletabilerin sarı üyesi olan 'Laa-Laa' olduğunu görür. Sinirlenerek yere bir tekme atar, arkadaşını kaybetmenin üzüntüsünü yaşar; elinde kalan tek şey, silahı ve onunla yaşadığı anılardır.")
} else {
    alert("Koray sakince silahını tutmaya devam eder ve çok hızlı bir hamle ile kafasının denk geldiği yere doğru bir mermi ateşler; camdan yere yığıldığını görür, hemen yanına gider; yere yığılan canavar, Teletabilerin sarı üyesi 'Laa-Laa'dır. Bu olayları yaşarken bir anda bağırma sesi duyulur; koşarak Nihat'a doğru baktığında, Teletabilerden 'Po'nun onu bıçakladığını ve aynı zamanda Nihat'ın da onu bıçakladığını görür; ikisi de kısa zamanda derin yaralara yol açtıkları için can verirler. Koray yere bir tekme vurarak arkadaşını kaybetmenin üzüntüsünü yaşar; elinde kalan tek şey, silahı ve onunla yaşadığı anılardır.")
}

alert("Hikayemiz burada bitmedi Yeşil olan teletabi hala ortalıkta yok arkadaşlarının intikamını alıcak mı yoksa kendi hayatına mı bakıcak her şey bölüm 2 de ...")